import DS from 'ember-data';

 var Post = DS.Model.extend({
  title: DS.attr('string'),
  title_image: DS.attr('string'),
  slug: DS.attr('string'),
  creator: DS.attr('string'),
  summary: DS.attr('string'),
  body: DS.attr('string'),
  created: DS.attr('date')
});

/*Post.reopenClass({
  FIXTURES: [
    {id: 1, creator: 'Vageesh', title: 'First Post', slug:'first-post', summary: 'Lorem ipsum Nulla sint laboris ad magna in.', body: '### What is Artsy? ###\r\n\r\n__Artsy__ is an umbrella term given by me for all my \'Eureka\' moments```hello```. \r\n```bash\r\n$ npm install\r\n```\r\nArtsy is the grand picture, comprised of many small elements.\r\n\r\n---\r\n\r\n### What is \'Artsy - Blog\'? ###\r\n\r\n> A blog is an individual\'s voice among the online crowd. It\'s a personal website, where you write and discuss your activities, moments, adventures and stories. \r\n\r\n__\'Artsy - Blog\'__ is a blogging platform, created by me, to log my web activities, adventures and learnings. The application structure consists of:\r\n+ Server-Side - [Node.js](http://nodejs.org/)\r\n+ Application Development - [ExpressJS](http://expressjs.com/)\r\n+ Text-to-HTML - [marked](https://github.com/chjj/marked) and [markdown](https://daringfireball.net/projects/markdown/)\r\n+ Code Highlighting - [highlight.js](http://highlightjs.org/)\r\n\r\nThe blogging platform is still not complete and work is under-progress.\r\n\r\n---\r\n\r\n### Who am I? ###\r\n\r\n+ My name is __Vageesh__ \r\n+ You can contact me via __[email](mailto:vageesh_bhasin@outlook.com)__\r\n+ I am a computer programmer and an application developer from [India](http://en.wikipedia.org/wiki/National_Capital_Region_%28India%29)\r\n+ I like :\r\n    + Web applications\r\n    + Creating New Things\r\n    + Lists :)\r\n\r\n---\r\n```html\r\n<!DOCTYPE html><html><head><title>My Chat App</title><!-- CSS:START --><link rel="stylesheet" href="/custom.css" /><link rel="stylesheet" href="//netdna.bootstrapcdn.com/.css" /><!-- CSS:END --></head><body>```\r\n', created: '12-03-2013'},
    {id: 2, creator: 'Vageesh', title: 'Second Post', slug:'second-post', summary: 'Lorem ipsum Nulla sint laboris ad magna in.', body: 'Lorem ipsum Minim reprehenderit elit nisi exercitation mollit dolore Duis consectetur elit sed sit dolor sed labore ad ut in magna magna dolor veniam esse cupidatat nulla irure dolore in ea ut commodo eiusmod elit commodo aliquip aliqua tempor commodo deserunt enim sunt adipisicing do deserunt Ut in consequat qui anim voluptate amet nulla in occaecat irure consectetur laborum id incididunt ad sint commodo aliquip proident ut nostrud laboris non Ut ex aute do minim proident mollit eiusmod est ea dolor non proident ullamco sint in sint fugiat aliqua amet culpa minim sunt Duis ut incididunt Ut voluptate id laboris dolore fugiat deserunt eiusmod aliquip occaecat mollit ut cillum laboris dolore incididunt ullamco proident anim minim officia laboris consequat quis mollit dolor in amet ut Duis aute labore incididunt sunt dolore proident exercitation elit fugiat aute sunt eiusmod ut deserunt fugiat et ut occaecat nulla in elit sed dolor eu velit ea Ut in cillum in magna aliqua culpa Ut exercitation nisi in in exercitation et non pariatur elit veniam.', created: '02-19-2014'},
    {id: 3, creator: 'Vageesh', title: 'Third Post', slug:'third-post', summary: 'Lorem ipsum Nulla sint laboris ad magna in.', body: 'Lorem ipsum Minim reprehenderit elit nisi exercitation mollit dolore Duis consectetur elit sed sit dolor sed labore ad ut in magna magna dolor veniam esse cupidatat nulla irure dolore in ea ut commodo eiusmod elit commodo aliquip aliqua tempor commodo deserunt enim sunt adipisicing do deserunt Ut in consequat qui anim voluptate amet nulla in occaecat irure consectetur laborum id incididunt ad sint commodo aliquip proident ut nostrud laboris non Ut ex aute do minim proident mollit eiusmod est ea dolor non proident ullamco sint in sint fugiat aliqua amet culpa minim sunt Duis ut incididunt Ut voluptate id laboris dolore fugiat deserunt eiusmod aliquip occaecat mollit ut cillum laboris dolore incididunt ullamco proident anim minim officia laboris consequat quis mollit dolor in amet ut Duis aute labore incididunt sunt dolore proident exercitation elit fugiat aute sunt eiusmod ut deserunt fugiat et ut occaecat nulla in elit sed dolor eu velit ea Ut in cillum in magna aliqua culpa Ut exercitation nisi in in exercitation et non pariatur elit veniam.', created: '01-01-2014' },
    {id: 4, creator: 'Vageesh', title: 'Forth Post', slug:'forth-post', summary: 'Lorem ipsum Nulla sint laboris ad magna in.', body: 'Lorem ipsum Minim reprehenderit elit nisi exercitation mollit dolore Duis consectetur elit sed sit dolor sed labore ad ut in magna magna dolor veniam esse cupidatat nulla irure dolore in ea ut commodo eiusmod elit commodo aliquip aliqua tempor commodo deserunt enim sunt adipisicing do deserunt Ut in consequat qui anim voluptate amet nulla in occaecat irure consectetur laborum id incididunt ad sint commodo aliquip proident ut nostrud laboris non Ut ex aute do minim proident mollit eiusmod est ea dolor non proident ullamco sint in sint fugiat aliqua amet culpa minim sunt Duis ut incididunt Ut voluptate id laboris dolore fugiat deserunt eiusmod aliquip occaecat mollit ut cillum laboris dolore incididunt ullamco proident anim minim officia laboris consequat quis mollit dolor in amet ut Duis aute labore incididunt sunt dolore proident exercitation elit fugiat aute sunt eiusmod ut deserunt fugiat et ut occaecat nulla in elit sed dolor eu velit ea Ut in cillum in magna aliqua culpa Ut exercitation nisi in in exercitation et non pariatur elit veniam.', created: '01-01-2014' }
  ]
});*/

export default Post;